### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by naderio** [naderio/nativescript-socket.io#3]
## Android
- [X] connect
- [X] connect with options
- [X] disconnect
- [X] add event listener without acknowledgement
- [X] emit event without acknowledgement
- [X] add event listener with acknowledgement
- [X] emit event with acknowledgement
- [X] remove all event listeners
- [X] remove particular event listener
- [X] add one-time event listener
## iOS
- [X] connect
- [X] connect with options
- [X] disconnect
- [X] add event listener without acknowledgement
- [X] emit event without acknowledgement
- [X] add event listener with acknowledgement
- [X] emit event with acknowledgement
- [X] remove all event listeners
- [X] remove particular event listener
- [X] add one-time event listener

## TODO
- [ ] migrate to [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed)
- [ ] write tests or make [socket.io-client tests](https://github.com/socketio/socket.io-client/tree/master/test) work for this plugin
- [ ] make [verified](https://github.com/NativeScript/marketplace-feedback/blob/master/docs/verified-plugins.md)

**Comment by naderio** [comment]
| Feature | Android | iOS|
| --- | --- | --- |
| connect | yes | yes |
| connect with options | yes | WIP |
| disconnect | yes | WIP |
| add event listener without acknowledgement | yes | WIP |
| emit event without acknowledgement | yes | WIP |
| add event listener with acknowledgement | yes | WIP |
| emit event with acknowledgement | yes | WIP |
| remove all event listeners | bug (#2) | WIP |
| remove particular event listeners | bug (#2) | WIP |

**Comment by shiv19** [comment]
May I help you migrate to nativescript-plugin-seed @naderio ?

**Comment by naderio** [comment]
hi @shiv19, thank you for your initiative
I'm working on migration to nativescript-plugin-seed already, once I push the initial version I would need help with testing on iOS and writing tests for both platforms
